# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: JWST Validation Notebooks
author: STScI
logo:

html:
  google_analytics_id: 
  
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex
    
parse:                                                                                                                                                                                                               
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - html_image
    
# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib
  
  
# Information about where the book exists on the web
repository:
  url: https://grit.stsci.edu/gough/jwst-validation-notebooks-test/  # Online location of your book
  # path_to_book:  Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
sphinx:
  recursive_update: true
  config:
    html_theme_options:
      repository_provider: custom  
